apiVersion: v1
kind: Service
metadata:
  name: {{ template "couchdb.fullname" . }}-headless
  labels:
    {{- include "couchdb.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: couchdb
      port: {{ .Values.service.port }}
  selector:
    {{- include "couchdb.selectorLabels" . | nindent 4 }}
---
# Source: couchdb/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "couchdb.fullname" . }}
  labels:
    {{- include "couchdb.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  type: ClusterIP
  selector:
    {{- include "couchdb.selectorLabels" . | nindent 4 }}
