---
apiVersion:  apps/v1
kind: StatefulSet
metadata:
  name: {{ include "couchdb.fullname" . }}
  labels:
    {{- include "couchdb.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "couchdb.fullname" .}}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      {{- include "couchdb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "couchdb.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "couchdb.fullname" . }}
      containers:
        - name: couchdb
          image: "couchdb:3.1.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: couchdb
              containerPort: 5984
            - name: epmd
              containerPort: 4369
            - containerPort: 9100
          env:
            - name: COUCHDB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "couchdb.fullname" . }}
                  key: adminUsername
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "couchdb.fullname" . }}
                  key: adminPassword
            - name: COUCHDB_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "couchdb.fullname" . }}
                  key: cookieAuthSecret
            - name: ERL_FLAGS
              value: " -name couchdb  -setcookie monster "
          livenessProbe:
            httpGet:
              path: /_up
              port: 5984
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /_up
              port: 5984
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            {}
          volumeMounts:
          - name: readonly-config
            mountPath: /opt/couchdb/etc/default.d
          - name: config-storage
            mountPath: /opt/couchdb/etc/local.d
          - name: database-storage
            mountPath: /opt/couchdb/data
      volumes:
          
        - name: readonly-config
          configMap:
            name: default-db-couchdb
            items:
              - key: inifile
                path: chart.ini
              - key: seedlistinifile
                path: seedlist.ini
  volumeClaimTemplates:
    - metadata:
        name: config-storage
        labels:
        {{- include "couchdb.selectorLabels" . | nindent 10 }}
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "{{ .Values.persistence.config.size }}"
        storageClassName: "{{ .Values.persistence.config.storageClassName }}"
    - metadata:
        name: database-storage
        labels:
        {{- include "couchdb.selectorLabels" . | nindent 10 }}
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "{{ .Values.persistence.data.size }}"
        storageClassName: "{{ .Values.persistence.data.storageClassName }}"
